adminapp/urls.py
from django.urls import re_path

import adminapp.views as adminapp

from .apps import AdminappConfig

app_name = AdminappConfig.name

urlpatterns = [
    re_path(r"^$", adminapp.admin_main, name="admin_main"),
    re_path(r"^users/create/$", adminapp.UsersCreateView.as_view(), name="user_create"),
    re_path(r"^users/read/$", adminapp.UsersListView.as_view(), name="users"),
    re_path(r"^users/update/(?P<pk>\d+)/$", adminapp.UsersUpdateView.as_view(), name="user_update"),
    re_path(r"^users/delete/(?P<pk>\d+)/$", adminapp.UsersDeleteView.as_view(), name="user_delete"),
    re_path(r"^categories/create/$", adminapp.ProductCategoryCreateView.as_view(), name="category_create"),
    re_path(r"^categories/read/$", adminapp.categories, name="categories"),
    re_path(r"^categories/update/(?P<pk>\d+)/$", adminapp.ProductCategoryUpdateView.as_view(), name="category_update"),
    re_path(r"^categories/delete/(?P<pk>\d+)/$", adminapp.ProductCategoryDeleteView.as_view(), name="category_delete"),
    re_path(r"^products/create/category/(?P<pk>\d+)/$", adminapp.ProductCreateView.as_view(), name="product_create"),
    re_path(r"^products/read/category/(?P<pk>\d+)/$", adminapp.products, name="products"),
    re_path(r"^products/read/(?P<pk>\d+)/$", adminapp.ProductDetailView.as_view(), name="product_read"),
    re_path(r"^products/update/(?P<pk>\d+)/$", adminapp.ProductUpdateView.as_view(), name="product_update"),
    re_path(r"^products/delete/(?P<pk>\d+)/$", adminapp.ProductDeleteView.as_view(), name="product_delete"),
]

authnapp/urls.py
from django.urls import re_path

import authnapp.views as authnapp
from authnapp.apps import AuthnappConfig

app_name = AuthnappConfig.name

urlpatterns = [
    re_path(r"^login/$", authnapp.login, name="login"),
    re_path(r"^logout/$", authnapp.logout, name="logout"),
    re_path(r"^register/$", authnapp.register, name="register"),
    re_path(r"^edit/$", authnapp.edit, name="edit"),
    re_path(r"^verify/(?P<email>.+)/(?P<activation_key>\w+)/$", authnapp.verify, name="verify"),
]

basketapp/urls.py
from django.urls import re_path

import basketapp.views as basketapp
from basketapp.apps import BasketappConfig

app_name = BasketappConfig.name

urlpatterns = [
    re_path(r"^$", basketapp.basket, name="view"),
    re_path(r"^add/(?P<pk>\d+)/$", basketapp.basket_add, name="add"),
    re_path(r"^remove/(?P<pk>\d+)/$", basketapp.basket_remove, name="remove"),
    re_path(r"^edit/(?P<pk>\d+)/(?P<quantity>\d+)/$", basketapp.basket_edit, name="edit"),
]

logistic/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.urls import path, re_path

import mainapp.views as mainapp

urlpatterns = [
    re_path(r"^$", mainapp.main, name="main"),
    re_path(r"^blog/", mainapp.blog, name="blog"),
    re_path(r"^text/", mainapp.text, name="text"),
    re_path(r"^text2/", mainapp.text2, name="text2"),
    re_path(r"^services/", include("mainapp.urls", namespace="services")),
    re_path(r"^contact/", mainapp.contact, name="contact"),
    re_path(r"^auth/", include("authnapp.urls", namespace="auth")),
    re_path(r"^basket/", include("basketapp.urls", namespace="basket")),
    re_path(r"^admin/", include("adminapp.urls", namespace="admin")),
    re_path(r"^order/", include("ordersapp.urls", namespace="order")),
    path("", include("social_django.urls", namespace="social")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [re_path(r"^__debug__/", include(debug_toolbar.urls))]

mainapp/urls.py
from django.urls import re_path

import mainapp.views as mainapp

from .apps import MainappConfig

app_name = MainappConfig.name

urlpatterns = [
    re_path(r"^$", mainapp.services, name="index"),
    re_path(r"^category/(?P<pk>\d+)/$", mainapp.services, name="category"),
    re_path(r"^category/(?P<pk>\d+)/page/(?P<page>\d+)/$", mainapp.services, name="page"),
    re_path(r"^service/(?P<pk>\d+)/$", mainapp.service, name="service"),
]

ordersapp/urls.py
from django.urls import re_path

import ordersapp.views as ordersapp
from ordersapp.apps import OrdersappConfig

app_name = OrdersappConfig.name

urlpatterns = [
    re_path(r"^$", ordersapp.OrderList.as_view(), name="orders_list"),
    re_path(r"^create/$", ordersapp.OrderItemsCreate.as_view(), name="order_create"),
    re_path(r"^read/(?P<pk>\d+)/$", ordersapp.OrderRead.as_view(), name="order_read"),
    re_path(r"^update/(?P<pk>\d+)/$", ordersapp.OrderItemsUpdate.as_view(), name="order_update"),
    re_path(r"^delete/(?P<pk>\d+)/$", ordersapp.OrderDelete.as_view(), name="order_delete"),
    re_path(r"^forming/complete/(?P<pk>\d+)/$", ordersapp.order_forming_complete, name="order_forming_complete"),
    re_path(r"^product/(?P<pk>\d+)/price/$", ordersapp.get_service_price),
]

mainapp/models.py
from os import name

from django.db import models
from django.utils import timezone


class ServicesCategory(models.Model):
    name = models.CharField(verbose_name="name_category", max_length=32, unique=True)
    name_long = models.CharField(verbose_name="name_long", max_length=64)
    desc_category = models.TextField(verbose_name="description")
    is_active = models.BooleanField(verbose_name="category_is_active", db_index=True, default=True)

    def __str__(self):
        return self.name


class Services(models.Model):
    category = models.ForeignKey(ServicesCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name="services", max_length=128)
    image = models.ImageField(upload_to="services_images", blank=True)
    description = models.TextField(verbose_name="description", blank=True)
    lifting = models.CharField(verbose_name="lifting", max_length=32)
    price = models.DecimalField(verbose_name="price", max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name="quantity", default=0)
    is_active = models.BooleanField(verbose_name="services_activ", db_index=True, default=True)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

    @staticmethod
    def get_items():
        return Services.objects.filter(is_active=True).order_by("category", "name")


class News(models.Model):
    title = models.CharField(verbose_name="title_news", max_length=256)
    text = models.TextField(verbose_name="text_news")
    public_date = models.DateTimeField(False, default=timezone.now)

    def __str__(self):
        return f"{self.title} ({self.public_date})"


class Benefits(models.Model):
    title = models.CharField(verbose_name="name", max_length=128)
    desc = models.TextField(verbose_name="description", blank=True)


class Team(models.Model):
    full_name = models.CharField(verbose_name="full_name", max_length=256)
    profession = models.CharField(verbose_name="profession", max_length=256)
    photo = models.ImageField(upload_to="team_photo", blank=True)
    email = models.CharField(verbose_name="e-mail", max_length=128)
    phone = models.CharField(verbose_name="phone", max_length=20)


class Contacts(models.Model):
    city = models.CharField(verbose_name="city", max_length=256)
    phone = models.CharField(verbose_name="phone", max_length=20)
    email = models.CharField(verbose_name="e-mail", max_length=128)
    address = models.CharField(verbose_name="address", max_length=512)

mainapp/views.py
import datetime
import random

from django.conf import settings
from django.core.cache import cache
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import get_object_or_404, render
from django.views.decorators.cache import cache_page

from basketapp.models import Basket

from .models import Benefits, Contacts, News, Services, ServicesCategory, Team


def get_links_menu():
    if settings.LOW_CACHE:
        key = "links_menu"
        links_menu = cache.get(key)
        if links_menu is None:
            # print(f'caching {key}')
            links_menu = ServicesCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ServicesCategory.objects.filter(is_active=True)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f"category_{pk}"
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ServicesCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ServicesCategory, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = "services"
        services = cache.get(key)
        if services is None:
            services = Services.objects.filter(is_active=True, category__is_active=True).select_related("category")
            cache.set(key, services)
        return services
    else:
        return Services.objects.filter(is_active=True, category__is_active=True).select_related("category")


def get_product(pk):
    if settings.LOW_CACHE:
        key = f"services_{pk}"
        services = cache.get(key)
        if services is None:
            services = get_object_or_404(Services, pk=pk)
            cache.set(key, services)
        return services
    else:
        return get_object_or_404(Services, pk=pk)


def get_products_orederd_by_price():
    if settings.LOW_CACHE:
        key = "products_orederd_by_price"
        products = cache.get(key)
        if products is None:
            products = Services.objects.filter(is_active=True, category__is_active=True).order_by("price")
            cache.set(key, products)
        return products
    else:
        return Services.objects.filter(is_active=True, category__is_active=True).order_by("price")


def get_products_in_category_orederd_by_price(pk):
    if settings.LOW_CACHE:
        key = f"products_in_category_orederd_by_price_{pk}"
        products = cache.get(key)
        if products is None:
            products = Services.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by(
                "price"
            )
            cache.set(key, products)
        return products
    else:
        return Services.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by("price")


def main(request):
    title = "home"

    caterories = ServicesCategory.objects.all()
    services = get_products()[:4]
    news = News.objects.all()
    benefits_list = Benefits.objects.all()
    team = Team.objects.all()

    content = {
        "title": title,
        "caterories": caterories,
        "services": services,
        "benefits_list": benefits_list,
        "team": team,
        "news": news,
        "media_url": settings.MEDIA_URL,
    }
    return render(request, "mainapp/index.html", content)


def blog(request):
    title = "blog"

    news = News.objects.all()

    content = {
        "title": title,
        "news": news,
    }
    return render(request, "mainapp/blog.html", content)


def text(request):
    title = "Privacy Policy"
    content = {"title": title}
    return render(request, "mainapp/text.html", content)


def text2(request):
    title = "Terms & Conditions"
    content = {"title": title}
    return render(request, "mainapp/text-2.html", content)


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def get_hot_services():
    services = Services.objects.all()
    return random.sample(list(services), 1)[0]


def get_same_services():
    services = get_products()
    same_services = random.sample(list(services), 1)[0]
    same_list = services.exclude(pk=same_services.pk)[:3]
    return (same_services, same_list)


def get_popular_goods(services):
    popular_services = Services.objects.all().exclude(pk=services.pk)
    return random.sample(list(popular_services), 3)


def services(request, pk=None, page=1):
    title = "services"
    links_menu = get_links_menu()

    if pk is not None:
        if pk == "0":
            category = {"pk": 0, "name": "All"}
            services = get_products_orederd_by_price()
        else:
            category = get_category(pk)
            services = get_products_in_category_orederd_by_price(pk)

        paginator = Paginator(services, 2)
        try:
            services_paginator = paginator.page(page)
        except PageNotAnInteger:
            services_paginator = paginator.page(1)
        except EmptyPage:
            services_paginator = paginator.page(paginator.num_pages)
        content = {
            "title": title,
            "services": services_paginator,
            "category": category,
            "links_menu": links_menu,
            "media_url": settings.MEDIA_URL,
        }
        return render(request, "mainapp/services_list.html", content)
    hot_services = get_hot_services()
    content = {
        "title": title,
        "links_menu": links_menu,
        "media_url": settings.MEDIA_URL,
        "popular": get_popular_goods(hot_services),
        "hot": hot_services,
    }
    if pk:
        print(f"User select category: {pk}")
    return render(request, "mainapp/services.html", content)


def service(request, pk):
    title = "service"

    service = get_object_or_404(Services, pk=pk)
    content = {
        "title": title,
        "links_menu": ServicesCategory.objects.all(),
        "service": service,
        "popular": get_popular_goods(service),
        "media_url": settings.MEDIA_URL,
    }
    return render(request, "mainapp/service.html", content)


@cache_page(600)
def contact(request):
    title = "contacts"
    visit_date = datetime.datetime.now()
    contacts = Contacts.objects.all()
    content = {
        "title": title,
        "visit_date": visit_date,
        "contacts": contacts,
    }
    return render(request, "mainapp/contact.html", content)

mainapp/templates/mainapp/includes/inc_categories_menu.html
<div class="categories__menu">

    <ul class="links__menu">

        <li class="{% if request.resolver_match.kwargs.pk == 0 %}active{% endif %}">
            <a href="{% url 'services:category' pk=0 %}">
                all
            </a>
        </li>
        
        {% for link in links_menu %}
            <li class="{% if request.resolver_match.kwargs.pk == link.pk %}active{% endif %}">
                <a href="{% url 'services:category' link.pk %}">
                {{ link.name }}
                </a>
            </li>
        {% endfor %}
        
     </ul>

</div>

mainapp/templates/mainapp/includes/inc_firstmenu.html
<nav class="nav" id='nav'>
    <a class="nav__link" href="#" data-scroll="#services">Services</a>
    <a class="nav__link" href="#" data-scroll="#clients">Clients</a>
    <a class="nav__link" href="#" data-scroll="#benefits">Benefits</a>
    <a class="nav__link" href="#" data-scroll="#team">Team</a>
    <a class="nav__link" href="#" data-scroll="#mission">Mission</a>
    <a class="nav__link" href="{% url 'services:index' %}">Products</a>
    <a class="nav__link" href="{% url 'contact' %}">Contact Us</a>

    {% if user.is_authenticated %}
    <div class="nav-item  dropdown  nav__link--drop">
        <a class="nav__link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">
            {{ user.first_name|default:'Пользователь' }}
            <span class="caret"></span>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'auth:edit' %}">{{ "профиль"|upper }}</a>
            <a class="dropdown-item" href="{% url 'order:orders_list' %}">{{ "Кабинет заказов"|upper }}</a>
        </div>
    </div>
    {% endif %}

    {% if user.is_superuser %}
        <a class="nav__link" href="{% url 'admin:users' %}">Admin</a>
    {% endif %}

    {% if user.is_authenticated %}
        <a class="nav__link" href="{% url 'auth:logout' %}">Logout</a>
    {% else %}
        <a class="nav__link" href="{% url 'auth:login' %}">Login</a>
    {% endif %}

    <a class="nav__link" href="#">
        <img class="search__img" src="/static/img/loupe_n.svg" alt="">
    </a>

    <a class="nav__link" href="{% url 'basket:view' %}">
        <img class="basket__img" src="/static/img/shopping-cart_n.svg" alt="">
        <span class="basket__count">
            {% if basket %} 
                {{ basket.0.total_cost|floatformat:0 }} руб ({{ basket.0.total_quantity }} шт) 
            {% endif %}
        </span>
    </a>

</nav>

mainapp/templates/mainapp/includes/inc_secondmenu.html
<nav class="nav" id='nav'>
    <a class="nav__link" href="{% url 'main' %}">Home</a>
    <a class="nav__link  {% if request.resolver_match.url_name == 'blog' %}active{% endif %}" href="{% url 'blog' %}">Blog</a>
    <a class="nav__link  {% if request.resolver_match.url_name == 'text2' %}active{% endif %}" href="{% url 'text2' %}">Terms &amp; Conditions</a>
    <a class="nav__link  {% if request.resolver_match.url_name == 'text' %}active{% endif %}" href="{% url 'text' %}">Privacy</a>
    <a class="nav__link  {% if request.resolver_match.namespace == 'services' %}active{% endif %}" href="{% url 'services:index' %}">Product</a>
    <a class="nav__link  {% if request.resolver_match.url_name == 'contact' %}active{% endif %}" href="{% url 'contact' %}">Contact Us</a>

    {% if user.is_authenticated %}
        <a class="nav__link" href="{% url 'auth:edit' %}">
            {{ user.first_name|default:'User' }}
        </a>
    {% endif %}

    {% if user.is_superuser %}
        <a class="nav__link" href="{% url 'admin:users' %}">Admin</a>
    {% endif %}

    {% if user.is_authenticated %}
        <a class="nav__link" href="{% url 'auth:logout' %}">Logout</a>
    {% else %}
        <a class="nav__link" href="{% url 'auth:login' %}">Login</a>
    {% endif %}

    <a class="nav__link" href="#">
        <img class="search__img" src="/static/img/loupe_n.svg" alt="">
    </a>

    <a class="nav__link" href="{% url 'basket:view' %}">
        <img class="basket__img" src="/static/img/shopping-cart_n.svg" alt="">
        <span class="basket__count">
            {% if basket %} 
                {{ basket.0.total_cost|floatformat:0 }} руб ({{ basket.0.total_quantity }} шт) 
            {% endif %}
        </span>
    </a>
</nav>