adminapp/urls.py
from django.urls import re_path

import adminapp.views as adminapp

from .apps import AdminappConfig

app_name = AdminappConfig.name

urlpatterns = [
    re_path(r"^$", adminapp.admin_main, name="admin_main"),
    re_path(r"^users/create/$", adminapp.UsersCreateView.as_view(), name="user_create"),
    re_path(r"^users/read/$", adminapp.UsersListView.as_view(), name="users"),
    re_path(r"^users/update/(?P<pk>\d+)/$", adminapp.UsersUpdateView.as_view(), name="user_update"),
    re_path(r"^users/delete/(?P<pk>\d+)/$", adminapp.UsersDeleteView.as_view(), name="user_delete"),
    re_path(r"^categories/create/$", adminapp.ProductCategoryCreateView.as_view(), name="category_create"),
    re_path(r"^categories/read/$", adminapp.categories, name="categories"),
    re_path(r"^categories/update/(?P<pk>\d+)/$", adminapp.ProductCategoryUpdateView.as_view(), name="category_update"),
    re_path(r"^categories/delete/(?P<pk>\d+)/$", adminapp.ProductCategoryDeleteView.as_view(), name="category_delete"),
    re_path(r"^products/create/category/(?P<pk>\d+)/$", adminapp.ProductCreateView.as_view(), name="product_create"),
    re_path(r"^products/read/category/(?P<pk>\d+)/$", adminapp.products, name="products"),
    re_path(r"^products/read/(?P<pk>\d+)/$", adminapp.ProductDetailView.as_view(), name="product_read"),
    re_path(r"^products/update/(?P<pk>\d+)/$", adminapp.ProductUpdateView.as_view(), name="product_update"),
    re_path(r"^products/delete/(?P<pk>\d+)/$", adminapp.ProductDeleteView.as_view(), name="product_delete"),
]

logistic/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.urls import path, re_path

import mainapp.views as mainapp

urlpatterns = [
    re_path(r"^$", mainapp.main, name="main"),
    re_path(r"^blog/", mainapp.blog, name="blog"),
    re_path(r"^text/", mainapp.text, name="text"),
    re_path(r"^text2/", mainapp.text2, name="text2"),
    re_path(r"^services/", include("mainapp.urls", namespace="services")),
    re_path(r"^contact/", mainapp.contact, name="contact"),
    re_path(r"^auth/", include("authnapp.urls", namespace="auth")),
    re_path(r"^basket/", include("basketapp.urls", namespace="basket")),
    re_path(r"^admin/", include("adminapp.urls", namespace="admin")),
    re_path(r"^order/", include("ordersapp.urls", namespace="order")),
    path("", include("social_django.urls", namespace="social")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [re_path(r"^__debug__/", include(debug_toolbar.urls))]

mainapp/urls.py
from django.urls import re_path

import mainapp.views as mainapp

from .apps import MainappConfig

app_name = MainappConfig.name

urlpatterns = [
    re_path(r"^$", mainapp.services, name="index"),
    re_path(r"^category/(?P<pk>\d+)/$", mainapp.services, name="category"),
    re_path(r"^category/(?P<pk>\d+)/page/(?P<page>\d+)/$", mainapp.services, name="page"),
    re_path(r"^service/(?P<pk>\d+)/$", mainapp.service, name="service"),
]

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms

from authnapp.forms import ShopUserEditForm
from authnapp.models import ShopUser
from mainapp.models import Services, ServicesCategory


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = "__all__"


class ProductCategoryEditForm(forms.ModelForm):
    discount = forms.IntegerField(label="скидка", required=False, min_value=0, max_value=90, initial=0)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            field.help_text = ""

    class Meta:
        model = ServicesCategory
        fields = "__all__"


class ProductEditForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProductEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            field.help_text = ""

    class Meta:
        model = Services
        fields = "__all__"

adminapp/views.py
from django.conf import settings
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import F
from django.shortcuts import HttpResponseRedirect, get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from adminapp.forms import ProductCategoryEditForm, ProductEditForm, ShopUserAdminEditForm
from authnapp.forms import ShopUserRegisterForm
from authnapp.models import ShopUser
from mainapp.models import Services, ServicesCategory


@user_passes_test(lambda u: u.is_superuser)
def admin_main(request):
    response = redirect("admin:users")
    return response


class UsersListView(LoginRequiredMixin, ListView):
    model = ShopUser
    template_name = "adminapp/users.html"


class UsersCreateView(LoginRequiredMixin, CreateView):
    model = ShopUser
    template_name = "adminapp/user_update.html"
    success_url = reverse_lazy("admin:users")
    # fields = "__all__"
    form_class = ShopUserRegisterForm

    def get_context_data(self, **kwargs):
        context = super(UsersCreateView, self).get_context_data(**kwargs)
        context["title"] = "пользователи/создание"
        return context


class UsersUpdateView(LoginRequiredMixin, UpdateView):
    model = ShopUser
    template_name = "adminapp/user_update.html"
    success_url = reverse_lazy("admin:user_update")
    form_class = ShopUserAdminEditForm

    def get_context_data(self, **kwargs):
        context = super(UsersUpdateView, self).get_context_data(**kwargs)
        context["title"] = "пользователи/редактирование"
        return context


class UsersDeleteView(LoginRequiredMixin, DeleteView):
    model = ShopUser
    template_name = "adminapp/user_delete.html"
    success_url = reverse_lazy("admin:users")

    def get_context_data(self, **kwargs):
        context = super(UsersDeleteView, self).get_context_data(**kwargs)
        context["title"] = "пользователи/удаление"
        return context

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


@user_passes_test(lambda u: u.is_superuser)
def categories(request):
    title = "админка/категории"
    categories_list = ServicesCategory.objects.all()
    content = {"title": title, "objects": categories_list, "media_url": settings.MEDIA_URL}
    return render(request, "adminapp/categories.html", content)


class ProductCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ServicesCategory
    template_name = "adminapp/category_update.html"
    success_url = reverse_lazy("admin:categories")
    fields = "__all__"


class ProductCategoryUpdateView(LoginRequiredMixin, UpdateView):
    model = ServicesCategory
    template_name = "adminapp/category_update.html"
    success_url = reverse_lazy("admin:categories")
    form_class = ProductCategoryEditForm

    def get_context_data(self, **kwargs):
        context = super(ProductCategoryUpdateView, self).get_context_data(**kwargs)
        context["title"] = "категории/редактирование"
        return context

    def form_valid(self, form):
        if "discount" in form.cleaned_data:
            discount = form.cleaned_data["discount"]
            if discount:
                # print(f"применяется скидка {discount}% к товарам категории {self.object.name}")
                self.object.services_set.update(price=F("price") * (1 - discount / 100))
                db_profile_by_type(self.__class__, "UPDATE", connection.queries)

        return super().form_valid(form)


class ProductCategoryDeleteView(LoginRequiredMixin, DeleteView):
    model = ServicesCategory
    template_name = "adminapp/category_delete.html"
    success_url = reverse_lazy("admin:categories")

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


@user_passes_test(lambda u: u.is_superuser)
def products(request, pk):
    title = "админка/продукт"
    category = get_object_or_404(ServicesCategory, pk=pk)
    products_list = Services.objects.filter(category__pk=pk).order_by("name")
    content = {"title": title, "category": category, "objects": products_list, "media_url": settings.MEDIA_URL}
    return render(request, "adminapp/products.html", content)


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Services
    template_name = "adminapp/product_update.html"
    success_url = reverse_lazy("admin:products")
    form_class = ProductEditForm

    def get_context_data(self, **kwargs):
        context = super(ProductCreateView, self).get_context_data(**kwargs)
        context["title"] = "продукт/создание"
        return context


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Services
    template_name = "adminapp/product_read.html"


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Services
    template_name = "adminapp/product_update.html"
    success_url = reverse_lazy("admin:product_update")
    form_class = ProductEditForm

    def get_context_data(self, **kwargs):
        context = super(ProductUpdateView, self).get_context_data(**kwargs)
        context["title"] = "продукт/редактирование"
        return context


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Services
    template_name = "adminapp/product_delete.html"
    success_url = reverse_lazy("admin:products")

    def get_context_data(self, **kwargs):
        context = super(ProductDeleteView, self).get_context_data(**kwargs)
        context["title"] = "продукт/удаление"
        return context

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


from django.db import connection
from django.db.models.signals import pre_save
from django.dispatch import receiver


def db_profile_by_type(prefix, type, queries):
    update_queries = list(filter(lambda x: type in x["sql"], queries))
    print(f"db_profile {type} for {prefix}:")
    [print(query["sql"]) for query in update_queries]


@receiver(pre_save, sender=ServicesCategory)
def service_is_active_update_servicecategory_save(sender, instance, **kwargs):
    if instance.pk:
        if instance.is_active:
            instance.services_set.update(is_active=True)
        else:
            instance.services_set.update(is_active=False)

        # db_profile_by_type(sender, 'UPDATE', connection.queries)

adminapp/templates/adminapp/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
        {{ title|title }}
        {% endblock %}
    </title>

    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}

    {% block js %}
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    {% endblock %}

</head>

<body>
    <div class="admin_container">
        <div class="h2 text-center head">
            Админка
        </div>
        {% block menu %}
        <div class="admin_menu">
            {% include 'adminapp/includes/inc_menu.html' %}
        </div>
        {% endblock %}


        {% block content %}
        {% endblock %}

    </div>
</body>

</html>

adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}

{% block content %}
<div class="categories_list">
    <a class="btn  btn-outline-primary  new__category  btn-sm " href="{% url 'admin:category_create' %}" role="button">новая категория</a>

    {% for object in objects %}
    <div class="category_record {% if not object.is_active %}not_active{% endif %}">
        <div class="category_name">
            {{ object.name|title }}
        </div>
        <div class="category_actions">
            <a class="btn  btn-outline-warning  btn-sm  m-1  w-100" href="{% url 'admin:products' object.pk %}" role="button">товары категории</a>
            <a class="btn  btn-outline-success  btn-sm  m-1  w-100" href="{% url 'admin:category_update' object.pk %}" role="button">редактировать</a>
            <a class="btn  text-danger  w-100" href="{% url 'admin:category_delete' object.pk %}" role="button">удалить</a>
        </div>
        <div class="category_desc">
            {{ object.description|title }}
        </div>
    </div>
    {% endfor %}

</div>
{% endblock %}

adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block content %}
<div class="category_delete">
    <p class="category_delete--text">Уверены, что хотите удалить категорию <strong>{{ object.name }}</strong>?</p> 
    <div class="category__form">
        <form action="{% url 'admin:category_delete' object.pk %}" method="post">
            {% csrf_token %}
            <input class="category__delete--delete  btn__admin  bg-danger  text-white" type="submit" value="удалить">
        </form>
        <a class="btn__admin  bg-success  text-white  category__delete--cancel  form-control" role="button" href="{% url 'admin:categories' %}">отмена</a>
    </div>
    
</div>
{% endblock %}

adminapp/templates/adminapp/category_update.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block content %}
<div class="new_category_form">
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="new_category_form--btn">
            <input class="form-control  bg-success  text-white  new_category_form--save" type="submit" value="сохранить">
        </div>
    </form>
    <div class="new_category_form--back_back">
        <button class="form-control  new_category_form--back" href="{% url 'admin:categories' %}">к списку категорий</button>
    </div>
</div>
{% endblock content %}

adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block content %}
<div class="product_delete">
    <p class="category_delete--text">Уверены, что хотите удалить продукт <strong>{{ object.name }}</strong>?</p>
    <div class="category__form">
        <form action="{% url 'admin:product_delete' object.pk %}" method="post">
            {% csrf_token %}
            <input class="category__delete--delete  btn__admin  bg-danger  text-white" type="submit" value="удалить">
        </form>
        <a class="btn__admin  bg-success  text-white  category__delete--cancel  form-control" href="{% url 'admin:products' object.category.pk %}" role="button">
            отмена
        </a>
    </div>
</div>
{% endblock %}

adminapp/templates/adminapp/product_read.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block content %}
<div class="product_read">
    <div class="product_name">
        Продукт<strong>{{ object.category.name|title }} / {{ object.name|title }}</strong>
    </div>
    <img src="/media/{{ object.image|default:'products_images/default.jpg' }}" alt="{{ object.name }}">
    <div class="summary">
        <b>цена</b>
        <p>{{ object.price }} руб</p>
        <b>количество</b>
        <p>{{ object.quantity }}</p>
        <b>в каталоге</b>
        <p>{% if object.is_active %}да{% else %}нет{% endif %}</p>
        <p>
            <a class="btn__admin  product-btn__reed  bg-warning  text-dark" href="{% url 'admin:product_update' object.pk %}" role="button">редактировать</a>
            <a class="btn__admin  product-btn__reed   text-danger" href="{% url 'admin:product_delete' object.pk %}" role="button">удалить</a>
            <a class="btn__admin  product-btn__reed   text-dark" href="{% url 'admin:products' object.category.pk %}">назад</a>
        </p>
    </div>
    <div class="product_desc">
        <b>краткая информация</b>
        <p>{{ object.short_desc }}</p><br><br>
        <b>подробная информация</b>
        <p>{{ object.description }}</p>
    </div>
</div>
{% endblock content %}

adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block content %}
<div class="new_category_form">
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="form-control" type="submit" value="сохранить">
    </form>
    <a href="{% url 'admin:products' object.pk %}" class="btn btn-outline-secondary btn-block my-3" role="button">
        к списку продуктов
    </a>
</div>
{% endblock %}

adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block content %}
<div class="products_list">
    <a class="btn__admin btn-outline-primary" href="{% url 'admin:product_update' category.pk %}" role="button">новый продукт</a>

    {% for object in objects %}
    <div class="product_record {% if not object.is_active %}not_active{% endif %}">
        <img class="product__record__img" src="{{ media_url }}{{ object.image|default:'services_images/default.jpg' }}" alt="{{ object.name }}">
        <div class="product_name">
            {{ object.name|title }}
        </div>
        <div class="product_actions">
            <a class="btn__admin  bg-warning text-dark" href="{% url 'admin:product_read' object.pk %}">подробнее</a>
            <a class="btn__admin  text-success" href="{% url 'admin:product_update' object.pk %}">редактировать</a>
            <a class="btn__admin  text-danger" href="{% url 'admin:product_delete' object.pk %}" role="button">удалить</a>
        </div>
        <div class="summary">
            <b>цена</b>
            <p>{{ object.price }} руб</p>
            <b>количество</b>
            <p>{{ object.quantity }}</p>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block content %}
<div class="user_delete">
    <p class="category_delete--text">
        Уверены, что хотите удалить {{ object.username }} 
        {% if object.first_name %}
        ({{ object.first_name|title }}</b>
        {% if object.last_name %}
        {{ object.last_name|title }}
        {% endif %})
        {% endif %}?
    </p>
    <div class="category__form">
        <form action="{% url 'admin:user_delete' object.pk %}" method="post">
            {% csrf_token %}
            <input class="category__delete--delete  btn__admin  bg-danger  text-white" type="submit" value="удалить">
        </form>
        <a class="btn__admin  bg-success  text-white  category__delete--cancel form-control" role="button" href="{% url 'admin:users' %}">отмена</a>
    </div>
</div>
{% endblock content %}

adminapp/templates/adminapp/user_update.html
{% extends 'authnapp/base.html' %}
{% load staticfiles %}


{% block content %}
<form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
</form>
<a class="btn btn-round form-control last" role="button" href="{% url 'admin:users' %}">
    к списку пользователей
</a>
{% endblock content %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block content %}
<div class="users_list">
    <a class="btn  btn-outline-primary" href="{% url 'admin:user_create' %}" role="button">новый пользователь</a>
    {% for object in object_list %}
    <div class="user_record {% if not object.is_active %}not_active{% endif %}">
        <img src="/media/{{ object.avatar|default:'users_avatars/Koala.jpg' }}" alt="{{ object.username }}">
        <div class="user_role">
            {% if object.is_superuser %}Администратор{% else %}пользователь{% endif %}
            <a class="btn  btn-outline-success  w-100  btn-sm  mt-4"  href="{% url 'admin:user_update' object.pk %}" role="button">редактировать</a>
            <a class="btn  text-danger  w-100  m-1" href="{% url 'admin:user_delete' object.pk %}" role="button">удалить</a>
        </div>
        <div class="user_name">
            <p>
                <strong>{{ object.username }}</strong>
            </p>
            <p>
                {% if object.first_name %}
                <b>{{ object.first_name|title }}</b>
                {% if object.last_name %}
                <p>{{ object.last_name|title }}</p>
                {% endif %}
                {% endif %}
            </p>
        </div>
        <div class="user_age">
            age:<br>
            {{ object.age }} лет
        </div>
        <div class="user_email">
            email:<br>
            {{ object.email }}
        </div>
        <div class="user_lastlogin">
            logged:<br>
            {{ object.last_login }}
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}