authnapp/urls.py
from django.urls import re_path

import authnapp.views as authnapp
from authnapp.apps import AuthnappConfig

app_name = AuthnappConfig.name

urlpatterns = [
    re_path(r"^login/$", authnapp.login, name="login"),
    re_path(r"^logout/$", authnapp.logout, name="logout"),
    re_path(r"^register/$", authnapp.register, name="register"),
    re_path(r"^edit/$", authnapp.edit, name="edit"),
    re_path(r"^verify/(?P<email>.+)/(?P<activation_key>\w+)/$", authnapp.verify, name="verify"),
]

basketapp/urls.py
from django.urls import re_path

import basketapp.views as basketapp
from basketapp.apps import BasketappConfig

app_name = BasketappConfig.name

urlpatterns = [
    re_path(r"^$", basketapp.basket, name="view"),
    re_path(r"^add/(?P<pk>\d+)/$", basketapp.basket_add, name="add"),
    re_path(r"^remove/(?P<pk>\d+)/$", basketapp.basket_remove, name="remove"),
    re_path(r"^edit/(?P<pk>\d+)/(?P<quantity>\d+)/$", basketapp.basket_edit, name="edit"),
]

logistic/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.urls import path, re_path

import mainapp.views as mainapp

urlpatterns = [
    re_path(r"^$", mainapp.main, name="main"),
    re_path(r"^blog/", mainapp.blog, name="blog"),
    re_path(r"^text/", mainapp.text, name="text"),
    re_path(r"^text2/", mainapp.text2, name="text2"),
    re_path(r"^services/", include("mainapp.urls", namespace="services")),
    re_path(r"^contact/", mainapp.contact, name="contact"),
    re_path(r"^auth/", include("authnapp.urls", namespace="auth")),
    re_path(r"^basket/", include("basketapp.urls", namespace="basket")),
    re_path(r"^admin/", include("adminapp.urls", namespace="admin")),
    re_path(r"^order/", include("ordersapp.urls", namespace="order")),
    path("", include("social_django.urls", namespace="social")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [re_path(r"^__debug__/", include(debug_toolbar.urls))]

mainapp/urls.py
from django.urls import re_path

import mainapp.views as mainapp

from .apps import MainappConfig

app_name = MainappConfig.name

urlpatterns = [
    re_path(r"^$", mainapp.services, name="index"),
    re_path(r"^category/(?P<pk>\d+)/$", mainapp.services, name="category"),
    re_path(r"^category/(?P<pk>\d+)/page/(?P<page>\d+)/$", mainapp.services, name="page"),
    re_path(r"^service/(?P<pk>\d+)/$", mainapp.service, name="service"),
]

mainapp/models.py
from os import name

from django.db import models
from django.utils import timezone


class ServicesCategory(models.Model):
    name = models.CharField(verbose_name="name_category", max_length=32, unique=True)
    name_long = models.CharField(verbose_name="name_long", max_length=64)
    desc_category = models.TextField(verbose_name="description")
    is_active = models.BooleanField(verbose_name="category_is_active", db_index=True, default=True)

    def __str__(self):
        return self.name


class Services(models.Model):
    category = models.ForeignKey(ServicesCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name="services", max_length=128)
    image = models.ImageField(upload_to="services_images", blank=True)
    description = models.TextField(verbose_name="description", blank=True)
    lifting = models.CharField(verbose_name="lifting", max_length=32)
    price = models.DecimalField(verbose_name="price", max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name="quantity", default=0)
    is_active = models.BooleanField(verbose_name="services_activ", db_index=True, default=True)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

    @staticmethod
    def get_items():
        return Services.objects.filter(is_active=True).order_by("category", "name")


class News(models.Model):
    title = models.CharField(verbose_name="title_news", max_length=256)
    text = models.TextField(verbose_name="text_news")
    public_date = models.DateTimeField(False, default=timezone.now)

    def __str__(self):
        return f"{self.title} ({self.public_date})"


class Benefits(models.Model):
    title = models.CharField(verbose_name="name", max_length=128)
    desc = models.TextField(verbose_name="description", blank=True)


class Team(models.Model):
    full_name = models.CharField(verbose_name="full_name", max_length=256)
    profession = models.CharField(verbose_name="profession", max_length=256)
    photo = models.ImageField(upload_to="team_photo", blank=True)
    email = models.CharField(verbose_name="e-mail", max_length=128)
    phone = models.CharField(verbose_name="phone", max_length=20)


class Contacts(models.Model):
    city = models.CharField(verbose_name="city", max_length=256)
    phone = models.CharField(verbose_name="phone", max_length=20)
    email = models.CharField(verbose_name="e-mail", max_length=128)
    address = models.CharField(verbose_name="address", max_length=512)

mainapp/views.py
import datetime
import random

from django.conf import settings
from django.core.cache import cache
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import get_object_or_404, render
from django.views.decorators.cache import cache_page

from basketapp.models import Basket

from .models import Benefits, Contacts, News, Services, ServicesCategory, Team


def get_links_menu():
    if settings.LOW_CACHE:
        key = "links_menu"
        links_menu = cache.get(key)
        if links_menu is None:
            # print(f'caching {key}')
            links_menu = ServicesCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ServicesCategory.objects.filter(is_active=True)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f"category_{pk}"
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ServicesCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ServicesCategory, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = "services"
        services = cache.get(key)
        if services is None:
            services = Services.objects.filter(is_active=True, category__is_active=True).select_related("category")
            cache.set(key, services)
        return services
    else:
        return Services.objects.filter(is_active=True, category__is_active=True).select_related("category")


def get_product(pk):
    if settings.LOW_CACHE:
        key = f"services_{pk}"
        services = cache.get(key)
        if services is None:
            services = get_object_or_404(Services, pk=pk)
            cache.set(key, services)
        return services
    else:
        return get_object_or_404(Services, pk=pk)


def get_products_orederd_by_price():
    if settings.LOW_CACHE:
        key = "products_orederd_by_price"
        products = cache.get(key)
        if products is None:
            products = Services.objects.filter(is_active=True, category__is_active=True).order_by("price")
            cache.set(key, products)
        return products
    else:
        return Services.objects.filter(is_active=True, category__is_active=True).order_by("price")


def get_products_in_category_orederd_by_price(pk):
    if settings.LOW_CACHE:
        key = f"products_in_category_orederd_by_price_{pk}"
        products = cache.get(key)
        if products is None:
            products = Services.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by(
                "price"
            )
            cache.set(key, products)
        return products
    else:
        return Services.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by("price")


def main(request):
    title = "home"

    caterories = ServicesCategory.objects.all()
    services = get_products()[:4]
    news = News.objects.all()
    benefits_list = Benefits.objects.all()
    team = Team.objects.all()

    content = {
        "title": title,
        "caterories": caterories,
        "services": services,
        "benefits_list": benefits_list,
        "team": team,
        "news": news,
        "media_url": settings.MEDIA_URL,
    }
    return render(request, "mainapp/index.html", content)


def blog(request):
    title = "blog"

    news = News.objects.all()

    content = {
        "title": title,
        "news": news,
    }
    return render(request, "mainapp/blog.html", content)


def text(request):
    title = "Privacy Policy"
    content = {"title": title}
    return render(request, "mainapp/text.html", content)


def text2(request):
    title = "Terms & Conditions"
    content = {"title": title}
    return render(request, "mainapp/text-2.html", content)


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def get_hot_services():
    services = Services.objects.all()
    return random.sample(list(services), 1)[0]


def get_same_services():
    services = get_products()
    same_services = random.sample(list(services), 1)[0]
    same_list = services.exclude(pk=same_services.pk)[:3]
    return (same_services, same_list)


def get_popular_goods(services):
    popular_services = Services.objects.all().exclude(pk=services.pk)
    return random.sample(list(popular_services), 3)


def services(request, pk=None, page=1):
    title = "services"
    links_menu = get_links_menu()

    if pk is not None:
        if pk == "0":
            category = {"pk": 0, "name": "All"}
            services = get_products_orederd_by_price()
        else:
            category = get_category(pk)
            services = get_products_in_category_orederd_by_price(pk)

        paginator = Paginator(services, 2)
        try:
            services_paginator = paginator.page(page)
        except PageNotAnInteger:
            services_paginator = paginator.page(1)
        except EmptyPage:
            services_paginator = paginator.page(paginator.num_pages)
        content = {
            "title": title,
            "services": services_paginator,
            "category": category,
            "links_menu": links_menu,
            "media_url": settings.MEDIA_URL,
        }
        return render(request, "mainapp/services_list.html", content)
    hot_services = get_hot_services()
    content = {
        "title": title,
        "links_menu": links_menu,
        "media_url": settings.MEDIA_URL,
        "popular": get_popular_goods(hot_services),
        "hot": hot_services,
    }
    if pk:
        print(f"User select category: {pk}")
    return render(request, "mainapp/services.html", content)


def service(request, pk):
    title = "service"

    service = get_object_or_404(Services, pk=pk)
    content = {
        "title": title,
        "links_menu": ServicesCategory.objects.all(),
        "service": service,
        "popular": get_popular_goods(service),
        "media_url": settings.MEDIA_URL,
    }
    return render(request, "mainapp/service.html", content)


@cache_page(600)
def contact(request):
    title = "contacts"
    visit_date = datetime.datetime.now()
    contacts = Contacts.objects.all()
    content = {
        "title": title,
        "visit_date": visit_date,
        "contacts": contacts,
    }
    return render(request, "mainapp/contact.html", content)

mainapp/templates/mainapp/base.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">

    <!-- Useful meta tags -->
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="index, follow, noodp">
    <meta name="googlebot" content="index, follow">
    <meta name="google" content="notranslate">
    <meta name="format-detection" content="telephone=no">
    <meta name="keywords" content="">
    <meta name="description" content="">

    <title>
        {% block title %}
        {{ title|capfirst }}
        {% endblock title %}
    </title>

    {% block css %}
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700;900&family=PT+Sans:wght@400;700&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    {% endblock css %}

</head>

<body>

    <div class="page">

        <header class="header" id="header">
            <div class="container">
                <div class="header__inner">
                    <a href="#" data-scroll="#intro">
                        <img class="img  header__img" src="{% static 'img/logo.svg' %}" alt="CenterLogistic">
                    </a>


                    {% block menu %}
                    {% endblock menu %}

                    <button class="burger" type="button" id="navToggle">
                        <span class="burger__line">1</span>
                        <span class="burger__line">2</span>
                        <span class="burger__line">3</span>
                        <span class="burger__line">4</span>
                    </button>

                </div>
                <!--./header__inner-->
            </div>
            <!--./container-->
        </header>

        <div class="content">

            {% block content %}
            {% endblock content %}

            <!-- Footer -->
            {% block footer %}
            <footer class="footer">
                <div class="container">
                    <img src="{% static 'img/logo-black.svg' %}" alt="">
                    <address class="footer__contacts">
                        <p>New York, Street, ZIP code</p>
                        <p>
                            Call Us: <a href="tel:+9948373123">+9948373123</a> or E-mail:
                            <a href="mailto:hello@centerlogistic.com">hello@centerlogistic.com</a>
                        </p>
                    </address>

                    <nav class="footer__nav">
                        <a href="/text2/">Terms &amp; Contidions</a>
                        <a href="/text/">Privacy Policy</a>
                        <a href="/blog/">Our blog</a>
                    </nav>
                </div>
            </footer>
            {% endblock footer %}

        </div>
        <!--./content-->

    </div>


    <!--Modal-->
    {% block modal %}
    <!--BecomeModal-->
    <div class="modal" id="becomeClientModal">
        <div class="modal__inner">
            <div class="modal__content">
                <div class="modal__header">
                    <h4 class="modal__title">Need to deliver your cargo?
                        We can help!</h4>
                    <div class="modal__text">
                        <p>Fill a little form and we will call you back!</p>
                    </div>
                </div>

                <form class="form" action="/" method="post">
                    <div class="form__group">
                        <input class="input input--dark input--user" type="text" placeholder="Your name">
                        <input class="input input--dark input--tel" type="tel" placeholder="Your phone">
                        <input class="input input--dark input--email" type="email" placeholder="Your email">
                    </div>
                    <button class="btn__main btn--block btn--orange" type="submit"> <span>Call me back</span>
                    </button>
                </form>

                <div class="modal__footer">
                    <h4 class="modal__footer-title">Our contacts</h4>
                    <address class="modal__contacts">
                        <p>New York, Street, ZIP code</p>
                        <p>Phone: <a href="tel:+9948373123">+9948373123</a></p>
                        <p>E-mail: <a href="mailto:hello@centerlogistic.com">hello@centerlogistic.com</a></p>
                    </address>
                </div>

                <button class="modal__close" type="button" data-modal-close>
                    <img src="/static/img/close.svg" alt="Close">
                </button>
            </div><!-- /.modal__content -->

        </div>
        <!--/.modal__inner-->
    </div>
    <!--/.becomeModal-->


    <!--ThanksModal-->
    <div class="modal" style="display: none" id="thanksModal">
        <div class="modal__inner">

            <div class="modal__header">
                <img class="modal__icon" src="/static/img/tick.svg" alt="">
                <h4 class="modal__title">Thanks for your request</h4>
                <div class="modal__text">
                    <p>We call you back as soon as possible!</p>
                </div>
            </div>

            <div class="modal__footer">
                <h4 class="modal__footer-title">Our contacts</h4>
                <address class="modal__contacts">
                    <p>New York, Street, ZIP code</p>
                    <p>Phone: <a href="tel:+9948373123">+9948373123</a></p>
                    <p>E-mail: <a href="mailto:hello@centerlogistic.com">hello@centerlogistic.com</a></p>
                </address>
            </div>

            <button class="modal__close" type="button">
                <img src="/static/img/close.svg" alt="Close">
            </button>


        </div>
        <!--/.modal__inner-->
    </div>
    <!--/.thanksModal-->
    {% endblock modal %}



    {% block js %}
    <!-- Javascript -->
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/app.js' %}"></script>
    <script src="{% static 'js/basket_script.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
        integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
        crossorigin="anonymous"></script>
    {% endblock js %}

</body>

</html>

mainapp/templates/mainapp/blog.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}


{% block menu %}
    {% include 'mainapp/includes/inc_secondmenu.html' %}
{% endblock menu %}

    
{% block content %}
    <!-- Intro -->
    <div class="intro intro--blog" id="intro">
    
    </div>
    
    
    <!-- Main -->
    <section class="section section--last">
        <div class="container">
            <main class="main">
                <div class="main__col">
                    <h1 class="section__title "><span class="section__title-blue">Interesting</span> to read</h1>
    
                    <div class="articles  articles--column">

                        {% for item in news %}
                            <article class="articles__item">
                                <h4 class="articles__title">
                                    <a href="{% url 'blog' %}">{{ item.title }}</a>
                                </h4>
                                <div class="articles__text">
                                    <p>{{ item.text }}</p>
                                </div>
                                <time class="articles_date" pubdate="21-03-2019 19:00">{{ item.public_date }}</time>
                            </article><!-- /.news__item -->
                        {% endfor %}
    
                    </div><!-- /.articles -->
    
                    <a class="btn__main  btn--orange" href="/">
                        <span>Back to home</span>
                    </a>
                </div><!-- /.main__col -->
    
                <div class="main__col">
                    <div class="request-form  request-form--right">
    
                        <div class="request-form__header">
    
                            <h3 class="request-form__title">Get Callback</h3>
                            <div class="request-form__text">
                                Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut
                            </div>
    
                            <div class="request-form__content">
                                <form class="form" action="/" method="post">
                                    <div class="form__group">
                                        <input class="input input--user" type="text" placeholder="Your name">
                                        <input class="input input--tel" type="tel" placeholder="Your phone">
                                        <input class="input input--email" type="email" placeholder="Your email">
                                    </div>
                                    <button class="bbtn__main tn btn--block btn--orange" type="submit">    <span>Call me back</span>
                                    </button>
                                </form>
                            </div><!-- ./request-form__content -->
    
                        </div><!-- /.request-form__header -->
    
                    </div><!-- /.request-form -->
                </div><!-- /.main__col -->
            </main>
    
    
    
        </div><!-- /.container -->
    </section>
{% endblock content %}

mainapp/templates/mainapp/service.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}


{% block menu %}
    {% include 'mainapp/includes/inc_secondmenu.html' %}
{% endblock menu %}

    
{% block content %}
    <!-- Services Intro -->
    <div class="intro intro--services" id="intro">
    
    </div>

    
    <!-- Content -->
    <section class="section section--gray" id="team" data-scrollspy="#team">
        <div class="container">
            {% include 'mainapp/includes/inc_categories_menu.html' %}

            <h2 class="section__title"><span class="section__title-blue">Our</span> car fleet</h2>
    
            <div class="team  intro__services">


                <!-- Detailed Service -->
                <div class="product__box">

                    <div class="product__left">
                        <img class="team__photo  img  services__photo" src="{{ media_url }}{{ service.image }}" alt="{{ service.name }}">
                    </div>

                    <div class="product__right">
                        <div class="product__name">{{ service.name }}</div>
                        <div class="team__prof">{{ service.description }}</div>
                        <div class="intro__services-lifting">
                            <img class="intro__services-icon" src="/static/img/lifting_auto.svg" alt="">
                            <p class="intro__services-text">{{ service.lifting }}</p>
                        </div>
                        <div class="wrap__btn  btn--hot">
                            <a class="btn__main  btn--block btn--orange btn--order" href="{% url 'basket:add' service.pk %}" type="button"><span>order</span></a>
                        </div>    
                    </div>

                </div><!-- /.team__col -->
            </div><!-- /.team -->

            <div class="wrapper_popular">
                <h2 class="popular_services">Popular goods</h3>

                <div class="team  intro__services">


                    {% for service in popular %}
                        <div class="team__col">
                            <div class="team__items  services__items" data-aos="fade-in">
                                <img class="team__photo  img  services__photo" src="{{ media_url }}{{ service.image }}" alt="{{ service.name }}">
                                <div class="team__name">{{ service.name }}</div>
                                <div class="team__prof">{{ service.description }}</div>
                                <div class="intro__services-lifting">
                                    <img class="intro__services-icon" src="/static/img/lifting_auto.svg" alt="">
                                    <p class="intro__services-text">{{ service.lifting }}</p>
                                </div>
                                <div class="wrap__btn">
                                    <a class="btn__main  btn--block btn--orange btn--order" href="{% url 'basket:add' service.pk %}" type="button"><span>order</span></a>
                                </div>
                            </div><!-- /.team__items -->
                        </div><!-- /.team__col -->
                    {% endfor %}
        
                </div><!-- /.team -->
            </div>

        </div><!-- /.container -->
    </section>
{% endblock content %}

mainapp/templates/mainapp/services.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}


{% block menu %}
    {% include 'mainapp/includes/inc_secondmenu.html' %}
{% endblock menu %}

    
{% block content %}
    <!-- Services Intro -->
    <div class="intro intro--services" id="intro">
    
    </div>

    
    <!-- Content -->
    <section class="section section--gray" id="team" data-scrollspy="#team">
        <div class="container">
            {% include 'mainapp/includes/inc_categories_menu.html' %}

            <h2 class="section__title"><span class="section__title-blue">Our</span> car fleet</h2>
    
            <!-- Hot price -->
            <div class="product__box">

                <div class="product__left">
                    <img class="team__photo  img  services__photo" src="{{ media_url }}{{ hot.image }}" alt="{{ hot.name }}">
                </div>

                <div class="product__right">
                    <div class="product__name">{{ hot.name }}</div>
                    <div class="team__prof">{{ hot.description }}</div>
                    <div class="intro__services-lifting">
                        <img class="intro__services-icon" src="/static/img/lifting_auto.svg" alt="">
                        <p class="intro__services-text">{{ hot.lifting }}</p>
                    </div>
                    <div class="hot_price">
                        <h3 class="red">горячее предложение</h3>
                    </div>
                    <div class="wrap__btn  btn--hot">
                        <a class="btn__main  btn--block btn--orange btn--order" href="{% url 'basket:add' hot.pk %}" type="button"><span>order</span></a>
                    </div>    
                </div>

            </div><!-- /.team__col -->


            <div class="wrapper_popular">
                <h2 class="popular_services">Popular goods</h3>

                <div class="team  intro__services">

                    {% for service in popular %}
                        <div class="team__col">
                            <div class="team__items  services__items" data-aos="fade-in">
                                <img class="team__photo  img  services__photo" src="{{ media_url }}{{ service.image }}" alt="{{ service.name }}">
                                <div class="team__name">{{ service.name }}</div>
                                <div class="team__prof">{{ service.description }}</div>
                                <div class="intro__services-lifting">
                                    <img class="intro__services-icon" src="/static/img/lifting_auto.svg" alt="">
                                    <p class="intro__services-text">{{ service.lifting }}</p>
                                </div>
                                <div class="wrap__btn">
                                    <a class="btn__main  btn--block btn--orange btn--order" href="{% url 'basket:add' service.pk %}" type="button"><span>order</span></a>
                                </div>
                            </div><!-- /.team__items -->
                        </div><!-- /.team__col -->
                    {% endfor %}
        
                </div><!-- /.team -->
            </div>

        </div><!-- /.container -->
    </section>
{% endblock content %}

mainapp/templates/mainapp/services_list.html
{% extends "mainapp/services.html" %}
{% load staticfiles %}

{% block content %}
<!-- Services Intro -->
<div class="intro intro--services" id="intro">
    
</div>

<div class="section section--gray">
    <div class="container">
        {% include "mainapp/includes/inc_categories_menu.html" %}

        <div class="services_list">
            <div class="title">
                <h2>Категория: "{{ category.name|title }}"</h2>
                <div class="paginator">
                    {% if services.has_previous %}
                    <a href="{% url 'services:page' category.pk services.previous_page_number %}"><i
                            class="fas fa-chevron-circle-left"></i></a>
                    {% endif %}
                    <span class="current">
                        страница {{ services.number }} из {{ services.paginator.num_pages }}
                    </span>
                    {% if services.has_next %}
                    <a href="{% url 'services:page' category.pk services.next_page_number %}"><i
                            class="fas fa-chevron-circle-right"></i></a>
                    {% endif %}
                </div>
            </div>
            <div class="category-services">

                {% for service in services %}
                <div class="team__col">
                    <div class="team__items  services__items" data-aos="fade-in">
                        <img class="team__photo  img  services__photo" src="{{ media_url }}{{ service.image }}" alt="{{ service.name }}">
                        <div class="team__name">{{ service.name }}</div>
                        <div class="team__prof">{{ service.description }}</div>
                        <div class="intro__services-lifting">
                            <img class="intro__services-icon" src="/static/img/lifting_auto.svg" alt="">
                            <p class="intro__services-text">{{ service.lifting }}</p>
                        </div>
                        <div class="wrap__btn">

                            {% if user.is_authenticated %}
                                <a class="btn__main  btn--block btn--orange btn--order" href="{% url 'services:service' service.pk %}" type="button"><span>order</span></a>
                                {% else %}
                                    <a class="btn__main  btn--block btn--orange btn--order" href="{% url 'auth:login' %}" type="button"><span>order</span></a>
                                    {% endif %}

                        </div>
                    </div><!-- /.team__items -->
                </div><!-- /.team__col -->
                {% endfor %}
            </div>
        </div>
    </div>

    
</div>

{% endblock %}